version: '3.8' # Indica la versión de Docker Compose

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

